### PR TITLE
Implement custom markup message for jenkins notifications

### PR DESCRIPTION
**Pull request by Sudelnuppe**
- change/rename customMessage to customAttachmentMessage
- add new customMessage with markup support
- add config fields for new customMessage

### CODE REVIEW

**Comment by jovandeginste** [comment]
@HusenBalter thanks for your time and work! Is this PR backward compatible? (Should I change configuration when using the merged code?)

**Comment by Sudelnuppe** [comment]
@jovandeginste Hi, the PR should be backward compatible (Renaming and add an optional new field).
Its just a new function, so you could but its not needed.

EDIT: I have noticed that some behavior could change. Because of the renaming, old values in the "Custom Message" are now send as Text with markup, instead of message in the Attachment. So you should change configuration.

**Comment by Sudelnuppe** [comment]
probably the PR fixes one issue: https://github.com/jovandeginste/jenkins-mattermost-plugin/issues/5
You can notify commiter/direct persons with '@username' on build fail now.

**Comment by jovandeginste** [comment]
@HusenBalter I built the hpi and installed it in my production setup; I will test it for a few days and if all is good, merge and publish.

**Comment by jovandeginste** [comment]
Because of holidays this took a little while longer, but it also means it was well tested :-)

Forging a release as I type this, so version 2.5.0 should hit your Jenkins somewhere today!

Thanks a lot @HusenBalter !

**Pull request merged**
