### PR TITLE
Merged HEAD on stash-plugin

### LINKED ISSUE #8: Jenkins Pipeline
Hi,

How do I get this to work with pipelines (if it's possible) ? I can't seem to find the docs for this.

For example, slack-plugin has this:
`slackSend color: 'good', message: 'Message from Jenkins Pipeline'`

TIA

### PR DESCRIPTION
**Pull request by eirikwang**
This pull-request merges the last version of the stash-plugin, to solve #8 .
Stash containes some webhook functionality, which is not included

Thiss pull-request fixes #8

### CODE REVIEW

**Comment by eirikwang** [comment]
Let me know if you want this pull-request squashed.

**Comment by jovandeginste** [comment]
One of the tests seems to fail:

```
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.075 sec <<< FAILURE! - in InjectedTest
index.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.028 sec  <<< ERROR!
org.apache.commons.jelly.JellyException: Could not parse Jelly script : file:/.autofs/homes/users/u0044579/projects/external/jenkins-mattermost-plugin/target/classes/index.jelly
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$TrailingMiscDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.jelly.parser.XMLParser.parse(XMLParser.java:350)
	at org.apache.commons.jelly.JellyContext.compileScript(JellyContext.java:525)
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:92)

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.972 sec - in jenkins.plugins.mattermost.workflow.MattermostSendStepIntegrationTest

Results :

Tests in error: 
  JellyTestSuiteBuilder$JellyCheck.runTest:92 » Jelly Could not parse Jelly scri...

Tests run: 29, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:10 min
[INFO] Finished at: 2016-07-14T13:52:24+02:00
[INFO] Final Memory: 47M/886M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project mattermost: There are test failures.
[ERROR] 
[ERROR] Please refer to /.autofs/homes/users/u0044579/projects/external/jenkins-mattermost-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jovandeginste** [comment]
@eirikwang when I checkout your PR and run `mvn install`, I get the following error:

```
[...]
Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.075 sec <<< FAILURE! - in InjectedTest
index.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.028 sec  <<< ERROR!
org.apache.commons.jelly.JellyException: Could not parse Jelly script : file:/.autofs/homes/users/u0044579/projects/external/jenkins-mattermost-plugin/target/classes/index.jelly
    at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentScannerImpl$TrailingMiscDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.apache.commons.jelly.parser.XMLParser.parse(XMLParser.java:350)
    at org.apache.commons.jelly.JellyContext.compileScript(JellyContext.java:525)
    at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:92)

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.972 sec - in jenkins.plugins.mattermost.workflow.MattermostSendStepIntegrationTest

Results :

Tests in error: 
  JellyTestSuiteBuilder$JellyCheck.runTest:92 » Jelly Could not parse Jelly scri...

Tests run: 29, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:10 min
[INFO] Finished at: 2016-07-14T13:52:24+02:00
[INFO] Final Memory: 47M/886M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project mattermost: There are test failures.
[ERROR] 
[ERROR] Please refer to /.autofs/homes/users/u0044579/projects/external/jenkins-mattermost-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jovandeginste** [comment]
OK, silly typo :-) I expected it to be something on my side ...

**Comment by eirikwang** [comment]
Yea. Silly typo :) 
I guess a failed attempt at committing from idea ;) ctrl-k -> k

**Comment by jovandeginste** [comment]
Like having ':wq' in a Word document ;-)

Anyway, compiled and deployed to our Jenkins setup. Will test it for a few days and if all is well I will merge the PR after the weekend...

**Comment by jovandeginste** [comment]
Took another week, but I'm building the release now (and if all goes well, it should be distributed around the world today)

**Pull request merged**
